version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_started
    env_file:
      - ./.env
    volumes:
      - ./src:/code/src
    networks:
      - appnet

  db:
    image: postgres:13
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - appnet

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    volumes:
      - ./:/app
    environment:
      - WEB=http://web:8080
    networks:
      - appnet

volumes:
  dbdata:


networks:
  appnet:
    driver: bridge
    name: appnet
