networks:
  appnet: {}
services:
  db:
    env_file:
      - ./.env
    image: postgres:13
    networks:
      appnet: null
    ports:
    - published: 5432
      target: 5432
    volumes:
    - dbdata:/var/lib/postgresql/data:rw
    - /home/haze/Development/animal-facts-api/migrations:/docker-entrypoint-initdb.d:rw
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
    environment:
      POSTGRES_DATABASE: unicorn
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: unicorn
    networks:
      appnet: null
    ports:
    - published: 8080
      target: 8080
    volumes:
    - /home/haze/Development/animal-facts-api/src:/code/src:rw
version: '3.8'
volumes:
  dbdata: {}