name: Black format check

on: [push]

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # Replace with the Python version you're using
      - name: Install Black
        run: python -m pip install black
      - name: Check code formatting
        run: black --check . # This command will check if your code is formatted with Black
